# Basic Airflow cluster configuration for CeleryExecutor with Redis and PostgreSQL.
#
# _AIRFLOW_WWW_USER_USERNAME   - Username for the administrator account (if requested).
#                                Default: airflow
# _AIRFLOW_WWW_USER_PASSWORD   - Password for the administrator account (if requested).
#                                Default: airflow
version: '3.2'

services:
  postgres:
    image: 'trial-postgres:2.0'
    command: postgres -c 'max_connections=600'
    build:
      context: ./docker-postgres  # Adjust this path to where your Postgres Dockerfile is located
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: airflow_user
      POSTGRES_PASSWORD: airflow_password
      POSTGRES_DB: airflow_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - airflow_network

networks:
  airflow_network:
    external:
      name: airflow_network